Drop py3.8 support | Replace pkg_resources lib with importlib.resources
openedx/crowdsourcehinter pull request #181
Opened 2024-09-23 07:44 UTC by beingfaisal

Issue - [Move on from deprecated pkg_resources api](https://github.com/openedx/crowdsourcehinter/issues/174)
Issue - [Drop Python 3.8 & Add Support for Python 3.12](https://github.com/openedx/crowdsourcehinter/issues/178)

- Drop python 3.8 support
- Replace pkg_resources with importlib

Screenshots
<img width="949" alt="Screenshot 2024-09-20 at 4 07 34 PM" src="https://github.com/user-attachments/assets/eda97b14-ac7f-4ffd-8254-6f18cbe319f3">
<img width="1675" alt="Screenshot 2024-09-20 at 4 08 09 PM" src="https://github.com/user-attachments/assets/85adec8c-e428-4fd6-bcd4-2a405c867604">

<img width="1699" alt="Screenshot 2024-09-20 at 4 07 15 PM" src="https://github.com/user-attachments/assets/c71b1442-a5bd-4839-8beb-d3ebfe185d73">

2024-09-23 12:39 UTC, farhan requested changes

2024-09-23 12:39 UTC, farhan commented on .travis.yml
> +- 3.11
I think we should add `3.12` support as well

2024-09-23 12:39 UTC, farhan commented on .travis.yml
> +- 3.11
Upgrade the version from `0.7` to `0.8`

2024-09-27 12:13 UTC, farhan approved these changes
Good work 🌟

2024-09-30 13:17 UTC, farhan approved these changes

2024-10-25 16:31 UTC, feanil approved these changes

2024-10-25 16:32 UTC, merged